name: First Workflow
on: [push]

jobs:
    run-shell-commands:
            runs-on: ubuntu-latest
            steps: 
                - name: echo a string
                  run: echo "Hello world"
                - name: Multiline Command
                  run: |
                    node -v
                    npm -v

    parallel-jobs:
      runs-on: macos-latest
      steps:
        - name: Run a script
          run: |
            echo "Hello world 2"

    dependent-jobs:
      runs-on: macos-latest
      needs: [run-shell-commands, parallel-jobs]
      steps:
        - name: Run a script
          run: |
            echo "Hello world 3"
      