name: ðŸ”„ Renovate Dependencies

on:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  renovate:
    name: ðŸ”„ Renovate Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v44.0.0
        with:
          configuration: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}