name: Renovate

on:
  schedule:
    - cron: '0 * * * *'  # 
  workflow_dispatch:       # Allow manual trigger

jobs:
  renovate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # optional: specify config file
          configurationFile: .github/renovate.json
        env:
          RENOVATE_REPOSITORIES: mandar-kanade/github-actions
          LOG_LEVEL: info