name: ðŸ”„ Renovate Dependencies

on:
  schedule:
    - cron: '0 2 * * *' # 2:00 AM UTC
  workflow_dispatch:

jobs:
  renovate:
    name: ðŸ”„ Renovate Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: verify renovate version
        run: |
          renovate --version

      - name: verify renovate config
        run: |
          renovate config lint

      - name: Run Renovate
        uses: renovatebot/github-action@v44.0.0
        with:
          token:  ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json